TOUCH_PAD_MACOS_SPEED = 220 # 101 | 210
TOUCH_PAD_MACOS_CONSISTENCY = 160 # 155

STANDARD_BRUSH_SIZE = 4
BRUSH_TYPE = 0 # 0 = Circle | 1 = Line

BOARD_X_DISSMENSION = 1200
BOARD_Y_DISSMENSION = 700

ICON_PATH = "../assets/asset2.png"

SAVE_FILE_PATH = "../out/"
SAVE_FILE_NAME = "miceink"
SAVE_FILE_EXT = "png"

TITLE = "Miceink"