# APP CONSTANTS 

TOUCH_PAD_MACOS_SPEED = 220 # 101 | 210
TOUCH_PAD_MACOS_CONSISTENCY = 170 # 155
TOUCH_PAD_MACOS_CONSISTENCY_BOOST = 13250

STANDARD_BRUSH_SIZE = 4
BRUSH_TYPE = 0 # 0 = Circle | 1 = Line

BOARD_COLOR = (255, 255,255)
BRUSH_COLOR = (0,0,0)

# HARD-CODE-CONSTANTS

BOARD_X_DISSMENSION = 1200
BOARD_Y_DISSMENSION = 700

FRAME_TICK = 30

ICON_PATH = "../assets/window_icon.png"

SAVE_FILE_PATH = "../out/"
SAVE_FILE_NAME = "feelink"
SAVE_FILE_EXT = "png"

TITLE = "FeelInk - Paperlike experince" 